package com.bitozen.hms.pm.common;

import java.util.Arrays;

public enum MVState {

    MV_INITIATE("MV INITIATE"),
    MV_SUBMISSION("MV SUBMISSION"),
    REQUEST_KCP_EO_APP("REQUEST KCP EO APPROVAL"),
    REQUEST_KCI_SOKL_APP("REQUEST KCI SOKL APPROVAL"),
    REQUEST_KCI_EO_APP("REQUEST KCI EO APPROVAL"),
    REQUEST_KPNO_EO_APP("REQUEST KPNO EO APPROVAL"),
    REQUEST_KPNO_DD_APP("REQUEST KPNO DD APPROVAL"),
    REQUEST_KPNO_ASSDIR_APP("REQUEST KPNO ASSDIR APPROVAL"),
    REQUEST_SDM_CABANG_APP("REQUEST SDM CABANG APPROVAL"),
    REQUEST_STAFFPENGEMBANGANSDM_APP("REQUEST STAFF PENGEMBANGAN SDM APPROVAL"),
    REQUEST_EO_BPO_APP("REQUEST EO BPO APPROVAL"),
    REQUEST_KCP_EO_NEW_APP("REQUEST KCP EO NEW APPROVAL"),
    REQUEST_KCI_EO_NEW_APP("REQUEST KCI EO NEW APPROVAL"),
    REQUEST_EO_BISNIS_AKUISISI_APP("REQUEST EO BISNIS AKUISISI APPROVAL"),
    REQUEST_EO_PLK_APP("REQUEST EO PLK APPROVAL"),
    REQUEST_KPNO_EO_NEW_APP("REQUEST KPNO EO NEW APPROVAL"),
    REQUEST_KPNO_DD_NEW_APP("REQUEST KPNO DD NEW APPROVAL"),
    REQUEST_KPNO_DEPUTY_DD_NEW_APP("REQUEST KPNO DEPUTY DD NEW APPROVAL"),
    REQUEST_KPNO_ASSDIR_NEW_APP("REQUEST KPNO ASSDIR NEW APPROVAL"),
    REQUEST_ASSDIR_OPERASI_APP("REQUEST ASSDIR OPERASI APPROVAL"),
    REQUEST_ASSDIR_RETAIL_APP("REQUEST ASSDIR RETAIL APPROVAL"),
    REQUEST_STAFFBPO_APP("REQUEST STAFFBPO APPROVAL"),
    REQUEST_DDSDM_APP("REQUEST DDSDM APPROVAL"),
    REQUEST_DEPUTYPRESDIR_APP("REQUEST DEPUTYPRESDIR APPROVAL"),
    REQUEST_KK_SOKL_NEW_APP("REQUEST KK SOKL NEW APPROVAL"),
    REQUEST_KCP_SOKL_NEW_APP("REQUEST KCP SOKL NEW APPROVAL"),
    REQUEST_KCI_SOKL_NEW_APP("REQUEST KCI SOKL NEW APPROVAL"),
    REQUEST_KPNO_DEPUTY_DD_APP("REQUEST KPNO DEPUTY DD APPROVAL"),
    REQUEST_DDCONSUMERRETAIL_APP("REQUEST DD CONSUMER RETAIL APPROVAL"),
    REQUEST_KPNO_DEPUTY_EO_NEW_APP("REQUEST KPNO DEPUTY EO NEW APPROVAL"),
    REQUEST_EO_DIKLAT_APP("REQUEST EO DIKLAT APPROVAL"),
    REQUEST_KPNO_ASSDIRDIR_APP("REQUEST KPNO ASSDIRDIR APPROVAL"),
    REQUEST_KPNO_ASSDIRDIR_NEW_APP("REQUEST KPNO ASSDIRDIR NEW APPROVAL"),
    REQUEST_DEPUTYPRESDIR_PRESDIR_APP("REQUEST DEPUTYPRESDIR PRESDIR APPROVAL"),
    REQUEST_KCP_SOKL_APP("REQUEST KCP SOKL APPROVAL"),
    REQUEST_KK_SOKL_APP("REQUEST KK SOKL APPROVAL")
    ;

    private String name;

    private MVState(String name) {
        this.name = name;
    }

    public MVState findEnum(String name) {
        return Arrays.stream(values())
                .filter(data -> data.name.equalsIgnoreCase(name))
                .findFirst()
                .orElse(null);
    }
}
