package com.bitozen.hms.pm.common;

import java.util.Arrays;

public enum MVState {

    MV_INITIATE("MV INITIATE"),
    MV_SUBMISSION("MV SUBMISSION"),
    REQUEST_KCP_EO_APPROVAL("REQUEST KCP EO APPROVAL"),
    REQUEST_KCI_SOKL_APPROVAL("REQUEST KCI SOKL APPROVAL"),
    REQUEST_KCI_EO_APPROVAL("REQUEST KCI EO APPROVAL"),
    REQUEST_KPNO_EO_APPROVAL("REQUEST KPNO EO APPROVAL"),
    REQUEST_KPNO_DD_APPROVAL("REQUEST KPNO DD APPROVAL"),
    REQUEST_KPNO_ASSDIR_APPROVAL("REQUEST KPNO ASSDIR APPROVAL"),
    REQUEST_SDM_CABANG_APPROVAL("REQUEST SDM CABANG APPROVAL"),
    REQUEST_STAFFPENGEMBANGANSDM_APPROVAL("REQUEST STAFF PENGEMBANGAN SDM APPROVAL"),
    REQUEST_EO_BPO_APPROVAL("REQUEST EO BPO APPROVAL"),
    REQUEST_KCP_EO_NEW_APPROVAL("REQUEST KCP EO NEW APPROVAL"),
    REQUEST_KCI_EO_NEW_APPROVAL("REQUEST KCI EO NEW APPROVAL"),
    REQUEST_EO_BISNIS_AKUISISI_APPROVAL("REQUEST EO BISNIS AKUISISI APPROVAL"),
    REQUEST_EO_PLK_APPROVAL("REQUEST EO PLK APPROVAL"),
    REQUEST_KPNO_EO_NEW_APPROVAL("REQUEST KPNO EO NEW APPROVAL"),
    REQUEST_KPNO_DD_NEW_APPROVAL("REQUEST KPNO DD NEW APPROVAL"),
    REQUEST_KPNO_DEPUTY_DD_NEW_APPROVAL("REQUEST KPNO DEPUTY DD NEW APPROVAL"),
    REQUEST_KPNO_ASSDIR_NEW_APPROVAL("REQUEST KPNO ASSDIR NEW APPROVAL"),
    REQUEST_ASSDIR_OPERASI_APPROVAL("REQUEST ASSDIR OPERASI APPROVAL"),
    REQUEST_ASSDIR_RETAIL_APPROVAL("REQUEST ASSDIR RETAIL APPROVAL"),
    REQUEST_STAFFBPO_APPROVAL("REQUEST STAFFBPO APPROVAL"),
    REQUEST_DDSDM_APPROVAL("REQUEST DDSDM APPROVAL"),
    REQUEST_DEPUTYPRESDIR_APPROVAL("REQUEST DEPUTYPRESDIR APPROVAL"),
    REQUEST_KK_SOKL_NEW_APPROVAL("REQUEST KK SOKL NEW APPROVAL"),
    REQUEST_KCP_SOKL_NEW_APPROVAL("REQUEST KCP SOKL NEW APPROVAL"),
    REQUEST_KCI_SOKL_NEW_APPROVAL("REQUEST KCI SOKL NEW APPROVAL"),
    REQUEST_KPNO_DEPUTY_DD_APPROVAL("REQUEST KPNO DEPUTY DD APPROVAL"),
    REQUEST_DDCONSUMERRETAIL_APPROVAL("REQUEST DD CONSUMER RETAIL APPROVAL"),
    REQUEST_KPNO_DEPUTY_EO_NEW_APPROVAL("REQUEST KPNO DEPUTY EO NEW APPROVAL"),
    REQUEST_EO_DIKLAT_APPROVAL("REQUEST EO DIKLAT APPROVAL"),
    REQUEST_KPNO_ASSDIRDIR_APPROVAL("REQUEST KPNO ASSDIRDIR APPROVAL"),
    REQUEST_KPNO_ASSDIRDIR_NEW_APPROVAL("REQUEST KPNO ASSDIRDIR NEW APPROVAL"),
    REQUEST_DEPUTYPRESDIR_PRESDIR_APPROVAL("REQUEST DEPUTYPRESDIR PRESDIR APPROVAL"),
    REQUEST_KCP_SOKL_APPROVAL("REQUEST KCP SOKL APPROVAL"),
    REQUEST_KK_SOKL_APPROVAL("REQUEST KK SOKL APPROVAL")
    ;

    private String name;

    private MVState(String name) {
        this.name = name;
    }

    public MVState findEnum(String name) {
        return Arrays.stream(values())
                .filter(data -> data.name.equalsIgnoreCase(name))
                .findFirst()
                .orElse(null);
    }
}
