package com.bitozen.hms.pm.common;

import java.util.Arrays;


public enum TerminationState {
    
    INITIATE("INITIATE"),
    REQ_KPNO_ASSDIR_APP("REQ_KPNO_ASSDIR_APPROVAL"),
    REQ_KK_SOKL_APP("REQ_KK_SOKL_APPROVAL"),
    REQ_KCP_SOKL_APP("REQ_KCP_SOKL_APPROVAL"),
    REQ_EODIKLAT_APP("REQ_EODIKLAT_APPROVAL"),
    REQ_ASSDIR_APP("REQ_ASSDIR_APPROVAL"),
    REQ_DEPUTYPRESDIR_APP("REQ_DEPUTYPRESDIR_APPROVAL"),
    REQ_SDMCABANG_APP("REQ_SDMCABANG_APPROVAL"),
    REQ_STAFFBPO_APP("REQ_STAFFBPO_APPROVAL"),
    REQ_DD_SDM_APP("REQ_DD_SDM_APPROVAL"),
    EXEC_RESIGN_EMPHEAD("EXEC_RESIGN_EMPHEAD"),
    EXEC_SDM_CABANG("EXEC_SDM_CABANG"),
    EXEC_RESIGN_EO_BPO("EXEC_RESIGN_EO_BPO"),
    CANCEL_EOHI_APP("CANCEL_EOHI_APPROVAL"),
    CANCEL_DDSM_APP("CANCEL_DDSM_APPROVAL"),
    CANCEL_STAFFBPO_APP("CANCEL_STAFFBPO_APPROVAL"),
    CANCEL_EODIKLAT_APP("CANCEL_EODIKLAT_APPROVAL"),
    CANCEL_SUBMISSION("CANCEL_SUBMISSION"),
    CANCEL_EMPHEAD_APP("CANCEL_EMPHEAD_APPROVAL"),
    CANCEL_SDMCABANG_APP("CANCEL_SDMCABANG_APPROVAL"),
    CANCEL_STAFFHI_APP("CANCEL_STAFFHI_APPROVAL"),
    EXEC_BIRODERIKSI("EXEC_BIRODERIKSI"),
    EXEC_PRESDIR("EXEC_PRESDIR"),
    JUDICALREVIEW_EMP2LV_EMPHEAD_APP("JUDICALREVIEW_EMP2LV_EMPHEAD_APPROVAL"),
    JUDICALREVIEW_SDMCABANG_APP("JUDICALREVIEW_SDMCABANG_APPROVAL"),
    JUDICALREVIEW_STFHI_APP("JUDICALREVIEW_STFHI_APPROVAL"),
    JUDICALREVIEW_EOHI_APP("JUDICALREVIEW_EOHI_APPROVAL"),
    JUDICALREVIEW_DDSM_APP("JUDICALREVIEW_DDSM_APPROVAL"),
    JUDICALREVIEW_STFPAYROLL_APP("JUDICALREVIEW_STFPAYROLL_APPROVAL"),
    REQ_KPNO_DD_APP("REQ_KPNO_DD_APPROVAL"),
    REQ_KPNO_EO_APP("REQ_KPNO_EO_APPROVAL"),
    REQ_KPNO_ASSDIRDIR_APP("REQ_KPNO_ASSDIRDIR_APPROVAL"),
    REQ_KPNO_DIR_APP("REQ_KPNO_DIR_APPROVAL"),
    REQ_PRESDIR_APP("REQ_PRESDIR_APPROVAL"),
    EXEC_EMP2LV("EXEC_EMP2LV"),
    EXEC_STFHI("EXEC_STFHI"),
    EXEC_EOHI("EXEC_EOHI"),
    EXEC_DDSM("EXEC_DDSM"),
    EXEC_STFPAYROLL("EXEC_STFPAYROLL"),
    EXEC_EOBPO("EXEC_EOBPO"),
    EXEC_STFBPO("EXEC_STFBPO"),
    EXEC_EXITITV("EXEC_EXITITV"),
    TMN_SUBMISSION("TMN_SUBMISSION"),
    EXEC_TMN_SUBMISSION("EXEC_TMN_SUBMISSION"),
    JUDICALREVIEW_SUBMISSION("JUDICALREVIEW_SUBMISSION"),
    EXEC_KPNO_DIR("EXEC_KPNO_DIR"),
    EXEC_STFPEMBUKUAN("EXEC_STFPEMBUKUAN"),
    REQ_KCP_EO_APP("REQ_KCP_EO_APPROVAL"),
    REQ_KCI_SOKL_APP("REQ_KCI_SOKL_APPROVAL"),
    REQ_KCI_EO_APP("REQ_KCI_EO_APPROVAL"),
    REQ_KPNO_DEPUTY_DD_APP("REQ_KPNO_DEPUTY_DD_APPROVAl"),
    EXEC_EODIKLAT("EXEC_EODIKLAT"),
    MEMO_EODIKLAT_APP("MEMO_EODIKLAT_APPROVAL"),
    MEMO_DDSM_APP("MEMO_DDSM_APPROVAL"),
    MEMO_STAFFBPO_APP("MEMO_STAFFBPO_APPROVAL"),
    MEMO_SUBMISSION("MEMO_SUBMISSION");
    
    private String name;
    
     private TerminationState(String name) {
        this.name = name;
    }

    public TerminationState findEnum(String name) {
        return Arrays.stream(values())
                .filter(data -> data.name.equalsIgnoreCase(name))
                .findFirst()
                .orElse(null);
    }
}
